#!/usr/bin/env tsx
/**
 * scripts/dev.ts
 *
 * Local-dev wrapper for `wrangler dev` (SPEC §0.5).
 *
 * The root wrangler.jsonc ships with empty resource IDs (`database_id: ""`,
 * `store_id: ""`) so the Deploy-to-Cloudflare auto-provisioner can fill them
 * in. Miniflare refuses to start with empty IDs, so this wrapper:
 *
 *   1. parses wrangler.jsonc (JSONC, comments allowed),
 *   2. fills empty IDs with stable local placeholders,
 *   3. writes the result to wrangler.dev.jsonc (generated — do not edit), and
 *   4. runs `wrangler dev --config wrangler.dev.jsonc`, passing through argv.
 *
 * The placeholder database_id also names the local D1 sqlite file under
 * .wrangler/state, so `pnpm migrate:local` and `pnpm seed` run against this
 * same generated config — otherwise they would hit a DIFFERENT local database
 * than the one `pnpm dev` serves.
 *
 * Flags (consumed here, anything else is passed through to wrangler):
 *   --config-only     materialize wrangler.dev.jsonc and exit (used by
 *                     `pnpm migrate:local`)
 *   --no-containers   set dev.enable_containers = false — UI/API work
 *                     without Docker running
 */

import { spawn } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as jsoncParser from 'jsonc-parser';

const ROOT = resolve(import.meta.dirname, '..');
const SRC = resolve(ROOT, 'wrangler.jsonc');
export const DEV_CONFIG_PATH = resolve(ROOT, 'wrangler.dev.jsonc');

/**
 * Generate wrangler.dev.jsonc from wrangler.jsonc with local placeholder IDs
 * filled in. Idempotent; returns the generated file's path.
 */
export function materializeDevConfig({ containers = true } = {}): string {
  const cfg = jsoncParser.parse(readFileSync(SRC, 'utf-8'));

  for (const secret of cfg.secrets_store_secrets ?? []) {
    if (!secret.store_id) secret.store_id = 'local-dev-store';
  }
  for (const db of cfg.d1_databases ?? []) {
    if (!db.database_id) db.database_id = 'local-dev-db';
  }
  if (!containers) {
    cfg.dev = { ...cfg.dev, enable_containers: false };
  }

  const header =
    '// GENERATED by scripts/dev.ts from wrangler.jsonc — do not edit, do not commit.\n';
  writeFileSync(DEV_CONFIG_PATH, `${header + JSON.stringify(cfg, null, 2)}\n`);
  return DEV_CONFIG_PATH;
}

const isMain =
  process.argv[1] != null && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMain) {
  const argv = process.argv.slice(2);
  const configOnly = argv.includes('--config-only');
  const noContainers = argv.includes('--no-containers');
  const passthrough = argv.filter((arg) => arg !== '--config-only' && arg !== '--no-containers');

  const configPath = materializeDevConfig({ containers: !noContainers });

  if (configOnly) {
    process.stdout.write(`${configPath}\n`);
    process.exit(0);
  }

  if (!existsSync(resolve(ROOT, 'apps/web/dist/index.html'))) {
    process.stderr.write(
      'apps/web/dist is missing — run `pnpm build` first (wrangler dev serves the built SPA).\n',
    );
    process.exit(1);
  }

  const child = spawn('wrangler', ['dev', '--config', configPath, ...passthrough], {
    cwd: ROOT,
    stdio: 'inherit',
  });
  child.on('exit', (code) => process.exit(code ?? 0));
}
